ROOT=..
ARCHIVE=ir
MODULE=ir

SRC_FILES= basic_block.cpp \
		   builder.cpp \
		   function.cpp \
		   instruction.cpp \
		   print_ir_visitor.cpp \
		   value.cpp

include $(ROOT)/mak/config.mak

include $(ROOT)/mak/archive.mak
